// Generated by uniffi-bindgen-react-native
#include "react-native-my-lib.h"
#include "generated/enums.hpp"
#include "generated/errors.hpp"
#include "generated/identifier.hpp"
#include "generated/identity.hpp"
#include "generated/pshenmic_dpp_v2_uniffi.hpp"

namespace mylib {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeEnums::registerModule(runtime, callInvoker);
		NativeErrors::registerModule(runtime, callInvoker);
		NativeIdentifier::registerModule(runtime, callInvoker);
		NativeIdentity::registerModule(runtime, callInvoker);
		NativePshenmicDppV2Uniffi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}